using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.3.1228.5055")]
[assembly: AssemblyFileVersionAttribute("1.3.1228.5055")]
[assembly: AssemblyCopyrightAttribute("Copyright © Brian Wight 2011-2012")]
[assembly: AssemblyProductAttribute("CloudInit")]
[assembly: AssemblyCompanyAttribute("Brian Wight")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyInformationalVersionAttribute("1.3.1228.5055")]
[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: ComVisibleAttribute(false)]

